baseurl = "https://forstmeier.github.io/buildwell/"
title = "Forstmeier"
author = "John Forstmeier"
languageCode = "en-us"
theme = "hugo-goa"
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  author = "John Forstmeier"
  intro = "Build well"
  description = "Project lead and core developer [@Heupr](https://github.com/heupr/)"
  authorimage = "thon.jpg"
  dateformat = "Feb 12,2017"

[params.meta]
  description = "John Forstmeier's personal website"
  keywords = "forstmeier,heupr,founder,golang,blog"

[params.social]
  twitter = "@forstmeier"
  github = "forstmeier"

[params.extra]
  copyright = "Copyright 2017 John Forstmeier"
  poweredBy = true
  highlightJS = true

[[menu.main]]
  name = "about"
  weight = 100
  url = "/about/"

# [[menu.main]]
#   name = "blog"
#   weight = 200
#   url = "/posts/"
#
# [[menu.main]]
#   name = "dev"
#   weight = 200
#   url = "/dev/"
#
# [[menu.main]]
#   name = "books"
#   weight = 300
#   url = "/books/"
#
# [[menu.main]]
#   name = "chess"
#   weight = 400
#   url = "/chess/"
