baseurl = "https://forstmeier.github.io/"
title = "John Forstmeier"
author = "John Forstmeier"
languagecode = "en-us"
theme = "hugo-goa"
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  author = "John Forstmeier"
  intro = "Build well"
  description = "Software Engineer and Data Scientist at [HeavyWater](https://www.heavywater.com/)"
  authorimage = "thon.jpg"
  dateformat = "Feb 12,2017"

[params.meta]
  description = "John Forstmeier's personal website"
  keywords = "john forstmeier,software engineer,data scientist,open source,creator,portfolio"

[params.social]
  twitter = "@forstmeier"
  github = "forstmeier"
  devto = "forstmeier"
  angellist = "forstmeier"
  instagram = "johnforstmeier"
  email = "john.forstmeier@gmail.com"

[params.extra]
  copyright = "Copyright 2018 John Forstmeier"
  poweredby = true
  highlightjs = true

[[menu.main]]
  name = "about"
  weight = 100
  url = "/about/"
