baseurl = "https://forstmeier.github.io/"
languageCode = "en-us"
title = "John Forstmeier"
theme = "ezhil"
pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
googleAnalytics = "UA-137861025-1"

[params]
  subtitle = "Build well 🛠️"
	recentPostsCount = 10
	excludedTypes = ["page"]
	disableDisqusTypes = ["page", "post"]
	featherIconsCDN = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 4

[[params.social]]
  name = "Github"
  icon = "github"
  url = "https://github.com/forstmeier"

[[params.social]]
  name = "Twitter"
  icon = "twitter"
  url = "https://twitter.com/@forstmeier"

[[params.social]]
  name = "Instagram"
  icon = "instagram"
  url = "https://www.instagram.com/johnforstmeier"

[[params.social]]
  name = "LinkedIn"
  icon = "linkedin"
  url = "https://www.linkedin.com/in/johnforstmeier"

[[params.social]]
  name = "Dev.to"
  icon = "terminal"
  url = "https://dev.to/@forstmeier"

[[params.social]]
  name = "AngelList"
  icon = "star"
  url = "https://angel.co/forstmeier"

[taxonomies]
  tag = "tags"
