baseurl = "https://forstmeier.github.io/"
title = "Forstmeier"
author = "John Forstmeier"
languagecode = "en-us"
theme = "hugo-goa"
canonifyurls = true

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  author = "John Forstmeier"
  intro = "Build well"
  description = "Co-creator and core developer [@Heupr](https://www.producthunt.com/upcoming/heupr)"
  authorimage = "thon.jpg"
  dateformat = "Feb 12,2017"

[params.meta]
  description = "John Forstmeier's personal website"
  keywords = "forstmeier,heupr,founder,golang,blog"

[params.social]
  twitter = "@forstmeier"
  github = "forstmeier"
  instagram = "johnforstmeier"

[params.extra]
  copyright = "Copyright 2017 John Forstmeier"
  poweredby = true
  highlightjs = true

[[menu.main]]
  name = "about"
  weight = 100
  url = "/about/"

# [[menu.main]]
#   name = "blog"
#   weight = 200
#   url = "/blog/"
#
# [[menu.main]]
#   name = "writings"
#   weight = 200
#   url = "/writings/"
#
# [[menu.main]]
#   name = "philosophy"
#   weight = 300
#   url = "/philosophy/"
