baseurl = "https://forstmeier.github.io/"
title = "John Forstmeier"
author = "John Forstmeier"
languagecode = "en-us"
theme = "hugo-goa"
canonifyurls = true
googleAnalytics = "UA-137861025-1"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

[params]
  author = "John Forstmeier"
  intro = "Build well"
  description = "Software Engineer and Data Scientist at [HeavyWater](https://www.heavywater.com/)"
  authorimage = "bridge.jpg"
  dateformat = "Jan 2, 2006"

[params.meta]
  description = "John Forstmeier's personal website"
  keywords = "john forstmeier, software engineer, open source, builder, creator, portfolio"

[params.social]
  twitter = "@forstmeier"
  github = "forstmeier"
  devto = "forstmeier"
  angellist = "forstmeier"
  linkedin = "johnforstmeier"
  instagram = "johnforstmeier"

[params.extra]
  copyright = "Copyright 2019 John Forstmeier"
  poweredby = true
  highlightjs = true

[[menu.main]]
  name = "about"
  weight = 100
  url = "/about/"

# [[menu.main]]
#   name = "notes"
#   weight = 200
#   url = "/notes/"
